apiVersion: v1
kind: Pod
metadata:
  name: external
spec:
  containers:
  - image: nginx
    name: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: internal
spec:
  containers:
  - image: nginx
    name: nginx

--- 
apiVersion: v1
kind: Pod
metadata:
  name: payroll
spec:
  containers:
  - image: nginx
    name: nginx

